"""
Execution engine base types — institutional order lifecycle data structures.

Models the full parent→child order decomposition used in institutional execution.
Parent orders represent portfolio-level intent; child orders represent individual
market interactions generated by execution algorithms.

Statistical assumptions:
- Fill prices always include slippage, spread, and impact components.
- Timestamps are monotonically increasing within an order lifecycle.
- No perfect fills: every execution has friction.
- Partial fills are modeled explicitly, not ignored.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum, unique
from typing import Any
from uuid import uuid4

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@unique
class OrderSide(Enum):
    BUY = "BUY"
    SELL = "SELL"


@unique
class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    MARKET_ON_CLOSE = "MOC"
    LIMIT_ON_CLOSE = "LOC"


@unique
class OrderStatus(Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


@unique
class ExecutionAlgorithm(Enum):
    TWAP = "TWAP"
    VWAP = "VWAP"
    PARTICIPATION = "PARTICIPATION"
    ICEBERG = "ICEBERG"
    IMMEDIATE = "IMMEDIATE"


@unique
class ExecutionUrgency(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    IMMEDIATE = "IMMEDIATE"


def _gen_id() -> str:
    return uuid4().hex[:16]


def _validate_positive(value: float, name: str) -> None:
    if not np.isfinite(value) or value < 0:
        raise ValueError(f"{name} must be non-negative finite, got {value}")


@dataclass(frozen=True)
class ParentOrder:
    """
    Portfolio-level order intent.

    A parent order captures what the portfolio construction engine wants:
    trade a specific quantity of an asset. The execution engine decomposes
    this into child orders according to the selected algorithm.

    No execution details here — those belong to the algorithm and child orders.
    """

    order_id: str = field(default_factory=_gen_id)
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    total_quantity: float = 0.0
    limit_price: float | None = None
    algorithm: ExecutionAlgorithm = ExecutionAlgorithm.TWAP
    urgency: ExecutionUrgency = ExecutionUrgency.MEDIUM
    start_time: pd.Timestamp | None = None
    end_time: pd.Timestamp | None = None
    max_participation_rate: float = 0.10
    created_at: pd.Timestamp = field(default_factory=lambda: pd.Timestamp.now(tz="UTC"))
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not np.isfinite(self.total_quantity) or self.total_quantity <= 0:
            raise ValueError(
                f"total_quantity must be positive finite, got {self.total_quantity}"
            )
        if self.limit_price is not None and (
            not np.isfinite(self.limit_price) or self.limit_price <= 0
        ):
            raise ValueError(f"limit_price must be positive finite, got {self.limit_price}")
        if not 0 < self.max_participation_rate <= 1.0:
            raise ValueError(
                f"max_participation_rate must be in (0,1], got {self.max_participation_rate}"
            )


@dataclass
class ChildOrder:
    """
    Single execution slice generated by an algorithm from a parent order.

    Child orders are mutable because they accumulate fill state.
    """

    child_id: str = field(default_factory=_gen_id)
    parent_id: str = ""
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: float = 0.0
    limit_price: float | None = None
    scheduled_time: pd.Timestamp | None = None
    slice_index: int = 0
    total_slices: int = 1
    status: OrderStatus = OrderStatus.PENDING
    quantity_filled: float = 0.0
    avg_fill_price: float = 0.0
    fill_events: list[FillEvent] = field(default_factory=list)
    created_at: pd.Timestamp = field(default_factory=lambda: pd.Timestamp.now(tz="UTC"))
    completed_at: pd.Timestamp | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def remaining_quantity(self) -> float:
        return max(0.0, self.quantity - self.quantity_filled)

    @property
    def fill_ratio(self) -> float:
        return self.quantity_filled / self.quantity if self.quantity > 0 else 0.0

    @property
    def is_complete(self) -> bool:
        return self.status in (
            OrderStatus.FILLED,
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.EXPIRED,
        )

    def apply_fill(self, fill: FillEvent) -> None:
        if self.is_complete:
            logger.warning("Applying fill to completed child order %s", self.child_id)
            return

        old_filled = self.quantity_filled
        new_filled = old_filled + fill.quantity_filled
        if new_filled > 0:
            self.avg_fill_price = (
                self.avg_fill_price * old_filled + fill.fill_price * fill.quantity_filled
            ) / new_filled
        self.quantity_filled = new_filled
        self.fill_events.append(fill)

        if abs(self.quantity_filled - self.quantity) < 1e-8:
            self.status = OrderStatus.FILLED
            self.completed_at = fill.timestamp
        else:
            self.status = OrderStatus.PARTIALLY_FILLED


@dataclass(frozen=True)
class FillEvent:
    """
    A single fill execution against a child order.

    All cost components are broken out for post-trade analysis.
    No hidden costs — every basis point is attributed.
    """

    fill_id: str = field(default_factory=_gen_id)
    child_id: str = ""
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    quantity_filled: float = 0.0
    fill_price: float = 0.0
    arrival_price: float = 0.0
    slippage_bps: float = 0.0
    spread_cost_bps: float = 0.0
    market_impact_bps: float = 0.0
    commission: float = 0.0
    total_cost: float = 0.0
    timestamp: pd.Timestamp = field(default_factory=lambda: pd.Timestamp.now(tz="UTC"))
    latency_ms: float = 0.0
    venue: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not np.isfinite(self.fill_price) or self.fill_price <= 0:
            raise ValueError(f"fill_price must be positive finite, got {self.fill_price}")
        if self.quantity_filled < 0:
            raise ValueError(
                f"quantity_filled must be non-negative, got {self.quantity_filled}"
            )

    @property
    def notional(self) -> float:
        return self.quantity_filled * self.fill_price

    @property
    def implementation_shortfall_bps(self) -> float:
        """Shortfall vs arrival price in basis points."""
        if self.arrival_price <= 0:
            return 0.0
        if self.side == OrderSide.BUY:
            return (self.fill_price - self.arrival_price) / self.arrival_price * 10_000
        return (self.arrival_price - self.fill_price) / self.arrival_price * 10_000


@dataclass
class ExecutionResult:
    """
    Aggregated result of executing a parent order.

    Tracks all child orders and fills, plus summary execution quality metrics.
    """

    parent_order: ParentOrder
    child_orders: list[ChildOrder] = field(default_factory=list)
    status: OrderStatus = OrderStatus.PENDING
    total_filled: float = 0.0
    avg_fill_price: float = 0.0
    total_slippage_bps: float = 0.0
    total_spread_cost_bps: float = 0.0
    total_impact_bps: float = 0.0
    total_commission: float = 0.0
    total_cost: float = 0.0
    vwap_price: float = 0.0
    start_time: pd.Timestamp | None = None
    end_time: pd.Timestamp | None = None
    warnings: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def fill_ratio(self) -> float:
        return (
            self.total_filled / self.parent_order.total_quantity
            if self.parent_order.total_quantity > 0
            else 0.0
        )

    @property
    def execution_duration_seconds(self) -> float:
        if self.start_time and self.end_time:
            return (self.end_time - self.start_time).total_seconds()
        return 0.0

    @property
    def is_complete(self) -> bool:
        return self.status in (
            OrderStatus.FILLED,
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.EXPIRED,
        )

    def aggregate_from_children(self) -> None:
        """Recompute summary stats from child order fills."""
        all_fills = [f for c in self.child_orders for f in c.fill_events]
        if not all_fills:
            return

        total_qty = sum(f.quantity_filled for f in all_fills)
        if total_qty <= 0:
            return

        self.total_filled = total_qty
        self.avg_fill_price = (
            sum(f.fill_price * f.quantity_filled for f in all_fills) / total_qty
        )
        self.vwap_price = self.avg_fill_price

        total_notional = sum(f.notional for f in all_fills)
        if total_notional > 0:
            self.total_slippage_bps = (
                sum(f.slippage_bps * f.notional for f in all_fills) / total_notional
            )
            self.total_spread_cost_bps = (
                sum(f.spread_cost_bps * f.notional for f in all_fills) / total_notional
            )
            self.total_impact_bps = (
                sum(f.market_impact_bps * f.notional for f in all_fills) / total_notional
            )

        self.total_commission = sum(f.commission for f in all_fills)
        self.total_cost = sum(f.total_cost for f in all_fills)

        timestamps = [f.timestamp for f in all_fills]
        self.start_time = min(timestamps)
        self.end_time = max(timestamps)

        if abs(self.total_filled - self.parent_order.total_quantity) < 1e-8:
            self.status = OrderStatus.FILLED
        elif self.total_filled > 0:
            self.status = OrderStatus.PARTIALLY_FILLED
